# Site settings
title: Nayeli Saupe Photography
email: nayeli@photosbynayeli.com
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed molestie et urna non condimentum. Pellentesque ultricies luctus sodales. Pellentesque tempus euismod egestas. Proin varius pretium nulla, ut ultrices odio vulputate eu. Sed sit amet finibus odio, eu faucibus elit.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nayelisaupe.com" # the base hostname & protocol for your site
twitter_username: nayelisaupe
instagram_username: nayeli_saupe_photography
facebook_username: PhotosByNayeli
profile_pic: /img/naye-001.jpg
white_logo: /img/logo-white.svg
black_logo: /img/logo-black.svg

# Build settings
markdown: kramdown
