# Site settings
title: Nayeli Saupe Photography
email: nayeli@nayelisaupe.com
description: Salt Lake City photographer that specializes in weddings, couples, and family sessions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nayelisaupe.com" # the base hostname & protocol for your site
twitter_username: nayelisaupe
instagram_username: nayeli_saupe_photography
facebook_username: PhotosByNayeli
profile_pic: /img/naye-001.jpg
white_logo: /img/logo-white.svg
black_logo: /img/logo-black.svg

# Build settings
markdown: kramdown

permalink: /:title
