# Site settings
title: Nayeli Saupe Photography
email: nayeli@photosbynayeli.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://photosbynayeli.com" # the base hostname & protocol for your site
twitter_username: nayelisaupe
instagram_username: nayeli_saupe_photography
facebook_username: PhotosByNayeli
profile_pic: /img/naye-001.jpg
white_logo: /img/logo-white.svg
black_logo: /img/logo-black.svg

# Build settings
markdown: kramdown

# Heroku stuff
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
